### PR TITLE
FIX: Don't assume the plugin folder is called `zendesk`

### PR DESCRIPTION
**Pull request by eviltrout**
The github repo is called `Zendesk-Plugin` and that will be the default
install directory for many people. This patch uses a relative `logs`
path so it doesn't matter what the plugin folder was called.

### CODE REVIEW

**Comment by shivpkumar** [comment]
Looks good. Thanks for the update, @eviltrout! Long time, no talk. Hope all is well :smile:

**Comment by eviltrout** [comment]
Everything is definitely well :) I might have some more PRs on this one coming. Just giving it a try now.

**Comment by shivpkumar** [comment]
Yup, I assume the plugin, as a whole, is pretty out of date. Do you have a Zendesk environment to test this with?

**Comment by shivpkumar** [comment]
Also, if you want to be super awesome, this repo could really use a README :wink:

**Comment by eviltrout** [comment]
No I don't have an environment but it might be the next step. I'm just checking it out for another client who is interested :)

**Pull request merged**
